# These are supported funding model platforms

github: mjohne
patreon: ortsfamilienbuecher_news
open_collective: # Replace with a single Open Collective username
ko_fi: ortsfamilienbuechernews
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: mjohne
issuehunt: mjohne
otechie: # Replace with a single Otechie username
custom: ['https://paypal.me/pools/c/8p8POmts3J','https://steadyhq.com/ortsfamilienbuechernews','https://flattr.com/@ofb.news']
